### ISSUE TITLE
Interface does not recognize category names containing slash character

### ISSUE THREAD

**Issue by wmde-manicki** [wmde/catgraph-jsonp#3]
I have come across this while testing the DeepCat-Gadget. When gadget sends a query concerning category containing slash (e.g. "AC/DC" in German Wikipedia) JSONP interface responses with 404.

This does not seem to be related to gadget itself (I mean gadget is apparently not breaking in the query itself), see: https://tools.wmflabs.org/catgraph-jsonp/dewiki_ns14/traverse-successors%20Category:AC/DC%2010%2050
First thing that came to my mind, namely urlescaping the slash character does not seem to help: https://tools.wmflabs.org/catgraph-jsonp/dewiki_ns14/traverse-successors%20Category:AC%2FDC%2010%2050 also gives 404

**Comment by jkroll20** [comment]
this happens in the URL handling, before the app even sees the request. this example would request the route "catgraph-jsonp/dewiki_ns14/traverse-successors Category:AC/DC", for which no handler is installed, of course.
i'll see what i can do about it.

**Comment by jkroll20** [comment]
There's a modifier for this in Flask: http://flask.pocoo.org/snippets/76/
fixed.
